image: maven:3-jdk-8

cache:
  paths:
    - /build/m2

before_script:
  - export MAVEN_REPO=/build/m2
  - apt-get update
  - apt-get install -y openjfx bc
  
stages:
  - build
  - test
#  - deploy
  
build-job:
  stage: build
  script:
    - mvn clean compile -B -Pit -Dmaven.repo.local=$MAVEN_REPO

unittest-job:
  stage: test
  script:
    - mvn clean test -B -Pit -Dmaven.repo.local=$MAVEN_REPO
    - echo "TotalUnitTestInstructionCoverage:" `cat target/site/jacoco/jacoco.xml | grep -E '<counter type="INSTRUCTION"[^>]*/>' -o | tail -n 1 | sed -E 's@<counter type="INSTRUCTION"[ ]+missed="([0-9]+)"[ ]+covered="([0-9]+)"[ ]*/>@scale=2;100*(\2)/(\1+\2)@' | bc`
    
integrationtest-job:
  stage: test
  script:
    - mvn clean verify -B -Pit -Dmaven.repo.local=$MAVEN_REPO
    - echo "TotalIntegrationTestInstructionCoverage:" `cat target/site/jacoco-it/jacoco.xml | grep -E '<counter type="INSTRUCTION"[^>]*/>' -o | tail -n 1 | sed -E 's@<counter type="INSTRUCTION"[ ]+missed="([0-9]+)"[ ]+covered="([0-9]+)"[ ]*/>@scale=2;100*(\2)/(\1+\2)@' | bc`    