language: java

sudo: false

jdk:
  - openjdk13
  - oraclejdk13

env:
  global:
    - MAVEN_PROFILES="it"

cache:
  directories:
    - $HOME/.m2

script: "mvn clean verify -P$MAVEN_PROFILES"

install: /bin/true

